/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flpCrowndsaleSol from "./FLPCrowndsale.sol";
export type { flpCrowndsaleSol };
export type { Floppy } from "./Floppy";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
